from info import *

# Bot settings
CACHE_TIME = ANUSHKA_CACHE_TIME 
USE_CAPTION_FILTER = ANUSHKA_USE_CAPTION_FILTER 

PICS = ANUSHKA_PICS 
NOR_IMG = ANUSHKA_NOR_IMG
MELCOW_VID = ANUSHKA_MELCOW_VID
SPELL_IMG = ANUSHKA_SPELL_IMG

# Admins, Channels & User
ADMINS = ANUSHKA_ADMINS
CHANNELS = ANUSHKA_CHANNELS
AUTH_USERS = ANUSHKA_AUTH_USERS
AUTH_GROUPS = ANUSHKA_AUTH_GROUPS
#support_chat_id = ANUSHKA_SUPPORT_CHAT_ID
REQST_CHANNEL = ANUSHKA_REQST_CHANNEL
SUPPORT_CHAT_ID = ANUSHKA_SUPPORT_CHAT_ID

#Downloader
DOWNLOAD_LOCATION = ANUSHKA_DOWNLOAD_LOCATION

# This is required for the plugins involving the file system.
TMP_DOWNLOAD_DIRECTORY = ANUSHKA_TMP_DOWNLOAD_DIRECTORY

# Open AI
OPENAI_API = ANUSHKA_OPENAI_API 

# Command
COMMAND_HAND_LER = ANUSHKA_COMMAND_HAND_LER

# MongoDB information
DATABASE_URI = ANUSHKA_DATABASE_URI 
DATABASE_NAME = ANUSHKA_DATABASE_NAME
COLLECTION_NAME = ANUSHKA_COLLECTION_NAME 

# stickers
STICKERS = ANUSHKA_STICKERS

# FSUB
AUTH_CHANNEL = ANUSHKA_AUTH_CHANNEL
# Set to  inside the bracket if you dont want to use Request Channel else set it to Channel ID
REQ_CHANNEL = ANUSHKA_REQ_CHANNEL
JOIN_REQS_DB = ANUSHKA_JOIN_REQS_DB

#Auto approve 
CHAT_ID = ANUSHKA_CHAT_ID
TEXT = ANUSHKA_TEXT
APPROVED = ANUSHKA_APPROVED

# Others
IS_VERIFY = ANUSHKA_IS_VERIFY 
VERIFY2_URL = ANUSHKA_VERIFY2_URL
VERIFY2_API = ANUSHKA_VERIFY2_API 
SHORTLINK_URL = ANUSHKA_SHORTLINK_URL
SHORTLINK_API = ANUSHKA_SHORTLINK_API 
IS_SHORTLINK = ANUSHKA_IS_SHORTLINK 
NO_RESULTS_MSG = ANUSHKA_NO_RESULTS_MSG 
DELETE_CHANNELS = ANUSHKA_DELETE_CHANNELS
MAX_B_TN = ANUSHKA_MAX_B_TN
MAX_BTN = ANUSHKA_MAX_BTN
PORT = ANUSHKA_PORT
S_GROUP = ANUSHKA_S_GROUP
RUL_LNK = ANUSHKA_RUL_LNK
MAIN_CHANNEL = ANUSHKA_MAIN_CHANNEL
GRP_LNK = ANUSHKA_GRP_LNK
CHNL_LNK = ANUSHKA_CHNL_LNK
OWN_LNK = ANUSHKA_S_GROUP
MVG_LNK = ANUSHKA_S_GROUP
MSG_ALRT = ANUSHKA_MSG_ALRT
LOG_CHANNEL = ANUSHKA_LOG_CHANNEL 
SUPPORT_CHAT = ANUSHKA_SUPPORT_CHAT
P_TTI_SHOW_OFF =ANUSHKA_P_TTI_SHOW_OFF
IMDB = ANUSHKA_IMDB 
AUTO_FFILTER = ANUSHKA_AUTO_FFILTER 
AUTO_DELETE = ANUSHKA_AUTO_DELETE 
SINGLE_BUTTON = ANUSHKA_SINGLE_BUTTON 
CUSTOM_FILE_CAPTION = ANUSHKA_CUSTOM_FILE_CAPTION
BATCH_FILE_CAPTION = ANUSHKA_BATCH_FILE_CAPTION
IMDB_TEMPLATE = ANUSHKA_IMDB_TEMPLATE
LONG_IMDB_DESCRIPTION = ANUSHKA_LONG_IMDB_DESCRIPTION
SPELL_CHECK_REPLY = ANUSHKA_SPELL_CHECK_REPLY
MAX_LIST_ELM = ANUSHKA_MAX_LIST_ELM
INDEX_REQ_CHANNEL = ANUSHKA_INDEX_REQ_CHANNEL
FILE_STORE_CHANNEL = ANUSHKA_FILE_STORE_CHANNEL
MELCOW_NEW_USERS = ANUSHKA_MELCOW_NEW_USERS
PROTECT_CONTENT = ANUSHKA_PROTECT_CONTENT
PUBLIC_FILE_STORE = ANUSHKA_PUBLIC_FILE_STORE

LANGUAGES = ANUSHKA_LANGUAGES
TUTORIAL = ANUSHKA_TUTORIAL
IS_TUTORIAL = ANUSHKA_IS_TUTORIAL 
